config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: 'registrations', controllers: {
    sessions: 'public/sessions'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_scope :customer do
    get 'edit' => 'public/registrations#edit'
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create'
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :categories, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    root to: 'homes#top'
    get '/search', to: 'search#search'
  end

  scope module: :public do
    #resource :customers, only: [:show, :edit, :update]
    get '/customers/quit' => 'customers#quit'
    patch '/customers/out' => 'customers#out'
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy, :show]
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :deliveries
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :phone_number, presence: true, format: {with: /\A\d{10,11}\z/}, numericality: true
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}, numericality: true
  validates :address, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def full_name
    last_name + first_name
  end

  def self.search_for(content, method)
    if method == 'forward'
      Customer.where('last_name LIKE ? OR first_name LIKE ?', content + '%',content + '%')
    elsif method == 'backward'
      Customer.where('last_name LIKE ? OR first_name LIKE ?', '%' + content,'%' + content)
    else
      Customer.where('last_name LIKE ? OR first_name LIKE ?', '%' + content + '%','%' + content + '%')
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(5)
   
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
    else
    render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-10">
      <h3 class="text-center" style="width:400px"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>

      <div class="form mt-5">
        <%= form_with model:[:admin, @customer], local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-row">
          <legend class="col-sm-3 col-form-label">会員ID</legend>
          <div class="form-group col-sm-4">
            <%= @customer.id %>
          </div>
        </div>
        <div class="form-row">
          <%= f.label :氏名, class:"col-sm-3 col-form-label" %>

          <div class="form-group col-sm-4">
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class:"form-control" %>
          </div>

          <div class="form-group col-sm-4">
            <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <%= f.label :フリガナ, class:"col-sm-3 col-form-label" %>
          <div class="form-group col-sm-4">
            <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class:"form-control" %>
          </div>
          <div class="form-group col-sm-4">
            <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <%= f.label :"郵便番号", class:"col-sm-3 col-form-label" %>
          <div class="form-group col-sm-4">
            <%= f.text_field :postcode, autofocus: true, autocomplete: "postcode", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <%= f.label :住所, class:"col-sm-3 col-form-label" %>
          <div class="form-group col-sm-9">
            <%= f.text_field :address, autofocus: true, autocomplete: "address", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <%= f.label :"電話番号", class:"col-sm-3 col-form-label" %>
          <div class="form-group col-sm-4">
            <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <%= f.label :メールアドレス, class:"col-sm-3 col-form-label" %>
          <div class="form-group col-sm-4">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control"  %>
          </div>
        </div>

        <div class="form-row">
          <%= f.label :会員ステータス, class:"col-sm-3 col-form-label" %>
          <div class="form-group col-sm-4">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, '有効', class:'mr-3' %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, '退会' %>
          </div>
        </div>

        <div class="form-group row">
            <legend class="col-3 col-form-label"></legend>
            <div class="col-3">
              <%= f.submit '変更を保存', class:'btn btn-success' %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h3 class="text-center" style="width:150px">会員一覧</h3>

      <table class="table mt-5">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.full_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <% if customer.is_deleted == true %>
              <td class="text-muted">退会</td>
            <% else %>
              <td class="text-success">有効</td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
          <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-10">
      <h3 class="text-center" style="width:400px"><%= @customer.full_name %>さんの会員詳細</h3>

      <table class="table mt-5 table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postcode %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <% if @customer.is_deleted == true %>
              <td class="text-muted">退会</td>
            <% else %>
              <td class="text-success">有効</td>
            <% end %>
          </tr>
          <tr>
            <td></td>
            <td><%= link_to '編集する', edit_admin_customer_path(@customer), class:'btn btn-success mr-5 px-3' %>
            <%= link_to '注文履歴一覧を見る', admin_root_path(customer_id: @customer.id), class:'btn btn-primary px-2' %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>