config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: 'registrations', controllers: {
    sessions: 'public/sessions'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_scope :customer do
    get 'edit' => 'public/registrations#edit'
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create'
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :categories, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    root to: 'homes#top'
    get '/search', to: 'search#search'
  end

  scope module: :public do
    #resource :customers, only: [:show, :edit, :update]
    get '/customers/quit' => 'customers#quit'
    patch '/customers/out' => 'customers#out'
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy, :show]
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  validates :select_address, acceptance: true

  with_options presence: true do
    validates :address, length: {maximum: 20, minimum: 2}
    validates :postcode, format: {with: /\A\d{7}\z/}, numericality: true
    validates :name
    validates :postage
    validates :total_payment
    validates :payment_method
    validates :status
  end


  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中":3, "発送済み":4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!


  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items.includes(:item)
    @total_price = @order_items.sum{|order_item|(order_item.price).round * order_item.amount }
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order.update(order_params)
    if @order.status == "入金待ち"
       @order_items.update_all(making_status: 0)
    elsif @order.status == "入金確認"
      @order_items.update_all(making_status: 1)
    end
     redirect_to admin_order_path(@order)
  end

  protected
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container mt-5">
  <div class="row">

    <div class="col-xs-offset-1">
 	    <table class="table">
	      <h4 class="mb-3">注文履歴詳細</h4>

			   <tr>
			  	 <th>購入者</th>
			  	 <td><%= link_to @order.customer.full_name, admin_customer_path(@order.customer_id) %></td>
			   </tr>

			   <tr>
			  	 <th>配送先</th>
			  	 <td>〒<%= @order.postcode + " " + @order.address %></td>
			   </tr>

			   <tr>
			  	 <th>支払い方法</th>
			  	 <td>
			  	   <% if @order.payment_method == 0 %>
		           <p>クレジットカード</p>
		  　      <% else %>
		           <p>銀行振り込み</p>
		         <% end %>
		       </td>
	       </tr>

			   <tr>
			  	 <th>注文ステータス</th>
			  	 <td>
			  	   <%#= form_for (@order), url: admin_order_path(@order), method: :patch do |f| %>
			  	   <%= form_with :model => @order, url: admin_order_path(@order), method: :patch, local: true  do |f| %>
			  	   <%= f.select :status, Order.statuses.keys.to_a %>
			  	   <%= f.submit "更新" , class: "btn btn-primary btn-sm" %>
	           <% end %>
			  	 </td>
			   </tr>
	    </table>
    </div>

    <div class = "col-md-9">
	    <table class="table">
			  <thead class="thead-light">
			  	<tr>
			  	<th>商品名</th>
			  	<th>単価（税込）</th>
			  	<th>数量</th>
			  	<th>小計</th>
			  	<th>制作ステータス</th>
			  	</tr>
			  </thead>

        <tbody>
			  	<% @order_items.each do |order_item| %>
			  	<%# @order.order_items.includes([:item])each do |order_item| %>
				  <tr>
				  	<td><%= order_item.item.name %></td>
				  	<td><%= addTax(order_item.item.price).to_s(:delimited) %></td>
				  	<td><%= order_item.amount %></td>
				  	<td><%= addTax(order_item.item.price * order_item.amount).to_s(:delimited) %></td>
				  	<td>
				  		<%#= form_for (order_item), url: admin_order_item_path(order_item), method: :patch do |f| %>
				  		<%= form_with :model => order_item, url: admin_order_item_path(order_item), method: :patch, local: true  do |f| %>
				  	  <%= f.select :making_status, OrderItem.making_statuses.keys.to_a %>
				  	  <%= f.submit "更新" , class: "btn btn-primary btn-sm" %>
				  	  <% end %>
				  	</td>
				  </tr>
				  <% end %>
	      </tbody>
	    </table>
    </div>

   <div class="col-md-3">
  	<table class="table total-price">
  	  <th class="col-xs-6">商品合計</th>
  	  <td><%= (@total_price).to_s(:delimited) %>円</td>
  	</tabale>
  	<table class="table freight">
  	  <th class="col-xs-6">送料</th>
  	  <td><%= @order.postage %>円</td>
  	</table>
  	<table class="table amount-billed">
  	  <th class="col-xs-6">請求金額合計</th>
  	  <td><%= (@total_price.to_i + @order.postage.to_i).to_s(:delimited) %>円</td>
  	</table>

    </div>
  </div>