config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: 'registrations', controllers: {
    sessions: 'public/sessions'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_scope :customer do
    get 'edit' => 'public/registrations#edit'
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create'
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :categories, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    root to: 'homes#top'
    get '/search', to: 'search#search'
  end

  scope module: :public do
    #resource :customers, only: [:show, :edit, :update]
    get '/customers/quit' => 'customers#quit'
    patch '/customers/out' => 'customers#out'
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy, :show]
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def sub_total_price
    (item.price * 1.1 * amount).round
  end


  validates :amount, presence: true, numericality: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :deliveries
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :phone_number, presence: true, format: {with: /\A\d{10,11}\z/}, numericality: true
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}, numericality: true
  validates :address, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def full_name
    last_name + first_name
  end

  def self.search_for(content, method)
    if method == 'forward'
      Customer.where('last_name LIKE ? OR first_name LIKE ?', content + '%',content + '%')
    elsif method == 'backward'
      Customer.where('last_name LIKE ? OR first_name LIKE ?', '%' + content,'%' + content)
    else
      Customer.where('last_name LIKE ? OR first_name LIKE ?', '%' + content + '%','%' + content + '%')
    end
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  with_options presence: true do
	  validates :postcode, format: {with: /\A\d{7}\z/}, numericality: true
	  validates :name
	  validates :address
	end

  def  total_address
  	"〒" + postcode + " " + address + "　" + name
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :cart_items

  attachment :image
  
  def self.search_for(content, method)
    if method == 'forward'
      Item.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Item.where('name LIKE ?', '%'+content)
    else
      Item.where('name LIKE ?', '%'+content+'%')
    end
  end

 with_options presence: true do
    validates :image
    #validates :category_id
    validates :name, length: {maximum: 20, minimum: 1}
    validates :information
    validates :price, numericality: true
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  validates :select_address, acceptance: true

  with_options presence: true do
    validates :address, length: {maximum: 20, minimum: 2}
    validates :postcode, format: {with: /\A\d{7}\z/}, numericality: true
    validates :name
    validates :postage
    validates :total_payment
    validates :payment_method
    validates :status
  end


  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中":3, "発送済み":4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    "着手不可": 0,
    "制作待ち": 1,
    "製作中": 2,
    "制作完了": 3
  }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all.page(params[:page]).per(10)
    @customer_orders = Order.where(customer_id: params[:customer_id])
    @customer = Customer.find_by(id: params[:customer_id])
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # binding.pry
    if @item.save
       flash[:notice] = "商品を登録しました。"
       redirect_to admin_item_path(@item)
    else
       render :new
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_items_path
      flash[:notice] = "商品を更新しました。"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :information, :image, :price, :is_active, :category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postcode,
      :address,
      :phone_number
      ])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def addTax(price)
    (price * 1.1).round
  end

end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "row justify-content-center">
	  <div class = "error">
	        <ul>
	            <% model.errors.full_messages.each do |message| %>
	               <li><%= message %></li>
	            <% end %>
	        </ul>
	    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>©All rights reserved by DMM</p>
</footer>

app/views/layouts/_header.html.erb
 <header>
    <nav class="navbar navbar-expand-lg">
    <div class="container">
      <!--<a class="navbar-brand text-dark" href="/" >NAGANOCAKE</a>-->
      <a href="/">
      <!--<img src="assets/logo.jpg" class="logo-img mr-2">-->
      <%= image_tag 'logo.jpg', class:"logo-img mr-2" %>
      </a>
      <% if customer_signed_in? %>
        <li class="list-unstyled">ようこそ、<%= current_customer.last_name.to_s + " " +current_customer.first_name.to_s %>さん！</li>
      <% end %>
      <!-- adminログイン後ヘッダー -->
      <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
        <nav>
         <ul class="navbar-nav">
            <li>
              <%= link_to admin_items_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-birthday-cake"></i>
                商品一覧
              <% end %>
            </li>
            <li>
              <%= link_to admin_customers_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-users"></i>
              会員一覧
              <% end %>
            </li>
            <li>
              <%= link_to admin_root_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-shopping-cart"></i>
                注文履歴
              <% end %>
            </li>
            <li>
              <%= link_to new_admin_category_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-caret-down"></i>
                ジャンル一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-out-alt"></i>
                ログアウト
              <% end %>
            </li>


          </ul>
        </nav>

      <!-- カスタマーログイン後 -->
      <% elsif customer_signed_in? %>
        <nav>
          <ul class="navbar-nav">
            <li>
              <%= link_to customer_path(current_customer), class: 'nav-link text-dark' do %>
                <i class="fas fa-house-user"></i>
                My Page
              <% end %>
            </li>
            <li>
              <%= link_to items_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-birthday-cake"></i>
                Line Up
              <% end %>
            </li>
            <li>
              <%= link_to cart_items_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-cart-plus"></i>
                Cart
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-out-alt"></i>
                Sign Out
              <% end %>
            </li>
          </ul>
        </nav>
      <% else %>
         <!-- admin、customerログイン前 -->
        <nav>
          <ul class="navbar-nav">
            <li>
              <%= link_to about_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-laptop-house"></i>
                About
              <% end %>
            </li>
            <li>
              <%= link_to items_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-birthday-cake"></i>
                Line Up
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-user-plus"></i>
                Sign Up
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-in-alt"></i>
                Sign In
              <% end %>
            </li>
          </ul>
        </nav>
      <% end %>
      </ul>
      </div>
    </div>
  </nav>
</header>
<div class="header-bottom"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-info">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <% if admin_signed_in? %>
    <div class="row justify-content-center mt-3 mb-3">
      <div class="search-form">
        <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :content %>
        <%= f.select :model, options_for_select({ "会員" => "customer", "商品" => "item" }) %>
        <%= f.select :method, options_for_select({ "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
        <%= f.submit '検索', class: 'btn btn-primary btn-sm' %>
        <% end %>
      </div>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>