config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: 'registrations', controllers: {
    sessions: 'public/sessions'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_scope :customer do
    get 'edit' => 'public/registrations#edit'
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create'
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :categories, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    root to: 'homes#top'
    get '/search', to: 'search#search'
  end

  scope module: :public do
    #resource :customers, only: [:show, :edit, :update]
    get '/customers/quit' => 'customers#quit'
    patch '/customers/out' => 'customers#out'
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy, :show]
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def sub_total_price
    (item.price * 1.1 * amount).round
  end


  validates :amount, presence: true, numericality: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :deliveries
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :phone_number, presence: true, format: {with: /\A\d{10,11}\z/}, numericality: true
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}, numericality: true
  validates :address, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def full_name
    last_name + first_name
  end

  def self.search_for(content, method)
    if method == 'forward'
      Customer.where('last_name LIKE ? OR first_name LIKE ?', content + '%',content + '%')
    elsif method == 'backward'
      Customer.where('last_name LIKE ? OR first_name LIKE ?', '%' + content,'%' + content)
    else
      Customer.where('last_name LIKE ? OR first_name LIKE ?', '%' + content + '%','%' + content + '%')
    end
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  with_options presence: true do
	  validates :postcode, format: {with: /\A\d{7}\z/}, numericality: true
	  validates :name
	  validates :address
	end

  def  total_address
  	"〒" + postcode + " " + address + "　" + name
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :cart_items

  attachment :image
  
  def self.search_for(content, method)
    if method == 'forward'
      Item.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Item.where('name LIKE ?', '%'+content)
    else
      Item.where('name LIKE ?', '%'+content+'%')
    end
  end

 with_options presence: true do
    validates :image
    #validates :category_id
    validates :name, length: {maximum: 20, minimum: 1}
    validates :information
    validates :price, numericality: true
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  validates :select_address, acceptance: true

  with_options presence: true do
    validates :address, length: {maximum: 20, minimum: 2}
    validates :postcode, format: {with: /\A\d{7}\z/}, numericality: true
    validates :name
    validates :postage
    validates :total_payment
    validates :payment_method
    validates :status
  end


  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中":3, "発送済み":4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    "着手不可": 0,
    "制作待ち": 1,
    "製作中": 2,
    "制作完了": 3
  }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all.page(params[:page]).per(10)
    @customer_orders = Order.where(customer_id: params[:customer_id])
    @customer = Customer.find_by(id: params[:customer_id])
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # binding.pry
    if @item.save
       flash[:notice] = "商品を登録しました。"
       redirect_to admin_item_path(@item)
    else
       render :new
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_items_path
      flash[:notice] = "商品を更新しました。"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :information, :image, :price, :is_active, :category_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!


  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items.includes(:item)
    @total_price = @order_items.sum{|order_item|(order_item.price).round * order_item.amount }
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order.update(order_params)
    if @order.status == "入金待ち"
       @order_items.update_all(making_status: 0)
    elsif @order.status == "入金確認"
      @order_items.update_all(making_status: 1)
    end
     redirect_to admin_order_path(@order)
  end

  protected
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController
  before_action :authenticate_admin!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'customer'
			@records = Customer.search_for(@content, @method)
		else
			@records = Item.search_for(@content, @method)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postcode,
      :address,
      :phone_number
      ])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def addTax(price)
    (price * 1.1).round
  end

end

app/views/admin/homes/top.html.erb
<div class='container'>
  <div class='row mt-5'>
    <div class='col'>
     <h3 class="text-center" style="width:200px" >注文履歴一覧</h3>

     <table class="table mt-5">
       <thead class="thead-light">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>ステータス</th>
        </tr>
        <% if @customer_orders.empty? %>
        <%# binding.pry %>
          <% if @customer.presence %>
          <% else %>
            <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admin_order_path(order) do %>
                <%= order.created_at.to_s(:datetime_jp) %>
                <% end %>
              </td>
              <td><%= order.customer.full_name %></td>
                <% @sum = 0 %>
              <td><% order.order_items.each do |order_item| %>
                <% @sum += order_item.amount %>
                <% end %>
                <%= @sum %>
              </td>
              <td><%= order.status %></td>
            </tr>
          <% end %>
       <% end %>
      <% else %>
        <% @customer_orders.each do |order| %>
      <tr>
        <td>
          <%= link_to admin_order_path(order) do %>
          <%= order.created_at.to_s(:datetime_jp) %>
          <% end %>
        </td>
        <td><%= order.customer.full_name %></td>
          <% @sum = 0 %>
        <td><% order.order_items.each do |order_item| %>
            <% @sum += order_item.amount %>
            <% end %>
            <%= @sum %>
        <td><%= order.status %></td>
      </tr>
       <% end %>
       <% end %>
     </table>
   </div>
  </div>
</div>

<div class="container page">
  <%= paginate @orders %>
</div>

app/views/admin/search/search.html.erb
<% if @model == 'customer' %>

  <div class="container">
	<h3>Customers search for "<%= @content %>"</h3>
  <div class="row mt-5">
    <div class="col">
      <h3 class="bg-light text-center" style="width:150px">会員一覧</h3>

      <table class="table mt-5">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @records.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.full_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <% if customer.is_deleted == true %>
              <td class="text-muted">退会</td>
            <% else %>
              <td class="text-success">有効</td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>
<% elsif @model == 'item' %>
	<h3>Items search for "<%= @content %>"</h3>
<div class="container">

<div style="position:absolute; top: 120px; right: 120px;">
	 <%= link_to new_admin_item_path do %>
		<div class="fas fa-plus-circle fa-3x"></div>
	 <% end %>
	 </div>

  <div class='row mt-5'>
    <div class='col'>
      <h3 class="bg-light text-center" style="width:150px" >商品一覧</h3>
       <table class="table mt-5">
        <thead class="thead-light">
         <tr class="table-light">
           <th>商品ID</th>
           <th>商品名</th>
           <th>税抜価格</th>
           <th>ジャンル</th>
           <th>ステータス</th>
         </tr>
        </thead>
        <tbody>
        <% @records.each do |item| %>
         <tr>
           <td><%= item.id %></td>
           <td>
             <%= link_to admin_item_path(item.id) do %>
             <%= item.name %>
             <% end %>
           </td>
           <td><%= item.price.to_s(:delimited) %></td>
           <td><%= item.category.name %></td>
           <td>
           <% if item.is_active? %>
            <p class="text-success">販売中</p>
           <% else %>
            <p class="text-secondary">販売停止中</p>
           <% end %>
          </td>
        </tr>
       <% end %>
       </tbody>
     </table>
   </div>
  </div>
</div>

<% end %>